### ISSUE TITLE
JAR files not remapping correctly while using unishadow plugin.

### ISSUE THREAD

**Issue by Scherso** [UnifyCraft/Gradle-Toolkit#1]
Post-compilation, while using a `.jar` file compiled with this Gradle toolkit, issues arise with `IChatComponent`. Minecraft's chat GUI does not render.

**Comment by Scherso** [comment]
ur shit doesn't work deftu

**Comment by Deftu** [comment]
Hey! I'm currently unsure of what causes this issue. I'm still looking into it and a fix will be deployed soon. We're just having some issues regarding Gradle and Kotlin.

**Comment by Deftu** [comment]
Fixed in c2e3ae84231c5473af653ef067ce7d7640d55b1f.
